### ISSUE TITLE
RoundedCorners have problem on lower divice

### ISSUE THREAD

**Issue by weidongjian** [wasabeef/glide-transformations#100]
devices: sony L36H android 4.2.2
```
GlideApp.with(this)
 .load(imageUrl)
 .placeholder(LoadingColorManager.getHotItemDrawable())
  .transform(new RoundedCorners(20))
 .into(imageView);
```

image become wired

![device-2017-10-12-172201](https://user-images.githubusercontent.com/6983015/31489130-4f7c03ee-af72-11e7-9b93-70e0419d868e.png)

**Comment by azri92** [comment]
Isn't RoundedCorners(int radius) from Glide instead of wasabeef's lib?
You should be using RoundedCornersTransformation(int radius, int margin) instead.
e.g.
```
GlideApp.with(this)
  .load(imageUrl)
  .placeholder(LoadingColorManager.getHotItemDrawable())
  .transform(new RoundedCornersTransformation(20, 0))
  .into(imageView);
```

**Comment by weidongjian** [comment]
I place the issue on wrong place
I use glide 4.2.0, and RoundedCornersTransformation isn't suitable for Glide 4.2.0
