### ISSUE TITLE
Behavior weird after upgraded to Glide 4.4

### ISSUE THREAD

**Issue by b95505017** [wasabeef/glide-transformations#107]
In my project, blur effect seems not working after upgraded to Glide 4.4.
Anyone meet the same issue here?

**Comment by Xenero** [comment]
It would have to be something you're doing wrong on your end and not the library itself as I have gotten this working out of the box with Glide 4.4. 

Glide 4.4 introduces some changes to the way effects are applied. See below for an example of how to blur an ImageView:

//Blur Image
if (dataArray.get(position).shouldBeBlurred()) {
Glide.with(getContext()).load(dataArray.get(position).getImageURL()).apply(RequestOptions.bitmapTransform(new BlurTransformation(25))).into(holder.imageView);
} else {
Glide.with(getContext()).load(dataArray.get(position).getImageURL()).into(holder.imageView);
}
