### ISSUE TITLE
Error using with Proguard

### ISSUE THREAD

**Issue by treylon** [wasabeef/glide-transformations#11]
Hey,

I tried to compile one of my projects using Proguard but it unfortunately failed. It would be great if you could provide a Proguard config file.

Cheers!

**Comment by squeeish** [comment]
Try adding this line?

-dontwarn jp.co.cyberagent.android.gpuimage.**

**Comment by heitorpr** [comment]
Well do not know why this issue is still open. The solution by @squeeish solved my problem here =).

**Comment by treylon** [comment]
Yeah works like a charm. Cheers man!
