### ISSUE TITLE
About RoundedCornerTransformation

### ISSUE THREAD

**Issue by sbqsbqsbq** [wasabeef/glide-transformations#110]
Hi Mr.wasabeef, I'm using your library to customize imageViews. However, I have a problem with rounded corner transformation. Especially, when i use rounded corner transformation into recycler view's item, transformation is applied to the only last item of recycler view. How can i solve this? The below is my code.

**Comment by johnaziz57** [comment]
@sbqsbqsbq the code is not pasted
