### ISSUE TITLE
when use "minifyEnabled true",can't success build apk.

### ISSUE THREAD

**Issue by super-qc** [wasabeef/glide-transformations#113]
Error:Execution failed for task ':app:transformClassesAndResourcesWithProguardForChannel_firRelease'.
> java.io.IOException: proguard.ParseException: Unknown option '-keepresourcexmlelements' in line 11 of file 'F:\punch_android_code\puncheer_android\app\build\intermediates\exploded-aar\jp.wasabeef\glide-transformations\3.0.0\proguard.txt'

**Comment by wasabeef** [comment]
@super-qc OK, Ill check that soon.

**Comment by wasabeef** [comment]
Can you try the new version of 3.1.1?
