### ISSUE TITLE
jp.wasabeef.glide.transformations.CropCircleTransformation is deprecated

### ISSUE THREAD

**Issue by quevon24** [wasabeef/glide-transformations#115]
Awesome library works great but I noticed that when I apply the transformation displays this message: jp.wasabeef.glide.transformations.CropCircleTransformation is deprecated

This will affect somehow functionality of the app?

Thanks

**Comment by wasabeef** [comment]
@quevon24 

I don't have the plan to delete CropCircleTransformation.
but I recommend that you should use the .circleCrop()  original of Glide.

like this.
```
GlideApp.with(context)
  .asBitmap()
  .load(canonical.getBitmap())
  .circleCrop()
  .override(50)
```
