### ISSUE TITLE
BlurTransformation with jpg

### ISSUE THREAD

**Issue by Stuart-campbell** [wasabeef/glide-transformations#13]
Hi,

Don't seem to be able to blur a jpg image.

Everything works great with a png. With the same code just changing the url to a jpg nothing happens

Working png example: http://i.stack.imgur.com/ILTQq.png
Not working jpg example: http://www.personal.psu.edu/jul229/mini.jpg

Problem on nexus 4 running lollipop.

Versions:
jp.wasabeef:glide-transformations:1.0.6@aar
jp.co.cyberagent.android.gpuimage:gpuimage-library:1.2.3@aar

Thanks in advance.

**Comment by tonilopezmr** [comment]
It's true!! Fix it!

**Comment by tonilopezmr** [comment]
It's true, @wasabeef fix it please.

**Comment by wasabeef** [comment]
I will try to fix it.

**Comment by tonilopezmr** [comment]
@Stuart-campbell "Everything works great with a png..."

That is false: 

Working png example: http://img02.deviantart.net/309b/i/2012/052/1/7/background_png_by_axemgr-d4qitne.png

Not working png example: http://img07.deviantart.net/a424/i/2014/161/6/e/total_drama_river_background_by_totaldramalegohd-d7lw56r.png

I think that the cause of why not works it's the size of images.

**Comment by sangrime** [comment]
Any updated version?
Thanks

**Comment by tonilopezmr** [comment]
No :-1: 

I'm waiting the new version for solve this issue

**Comment by wasabeef** [comment]
@sangrime 
@tonilopezmr 

Hi. what's your devices?

device is Nexus6 5.1.1
![](http://i.imgur.com/xRA1pN9.jpg)

**Comment by tonilopezmr** [comment]
Works! with the new version I have not problems. Thanks.

**Comment by wasabeef** [comment]
@tonilopezmr 

:shipit:
