### ISSUE TITLE
Library including the GPUImage library

### ISSUE THREAD

**Issue by alphamu** [wasabeef/glide-transformations#15]
From what I have been able to tell, you're library automatically includes the GPUImage library.
It shows up in the exploded-aar as well when your code is compiled.
It would be nice to fix this, my project has armeabi code in it, but doesn't have 64-bit support and since GPUImage includes 64-bit support, this resulted in the other library in my project not being found. I couldn't only exclude GPUImage as your library included it.

**Comment by wasabeef** [comment]
please check 1.2.0.
