### ISSUE TITLE
Is there a way to set blur effect before image load

### ISSUE THREAD

**Issue by beartistic** [wasabeef/glide-transformations#156]
hi there,

I wanna implement a loading effect using glide
like airbnb , set blur effect when image loading and then loaded(5ms later maybe look likes) remove blur effect 
I tried MultiTransformation<> use twice BlurTranformation through params value reduce but not work
I google it but never figure out
Is there a way?

**Comment by beartistic** [comment]
solved
I use glide(v4) thumb(0.01f) implement blur effect.

**Comment by fukemy** [comment]
can u provide code to do it? thanks
