### ISSUE TITLE
RoundedCornersTransformation not working 

### ISSUE THREAD

**Issue by leixinstar** [wasabeef/glide-transformations#16]
when CenterCrop ,RoundedCornersTransformation not working

**Comment by wasabeef** [comment]
@leixinstar 

Please tell me your source code.
the following code is sample.
```java
Glide.with(mContext)
  .load(R.drawable.demo)
  .bitmapTransform(new CenterCrop(mContext), new RoundedCornersTransformation(mContext, 100, 0))
  .into(holder.image);
```

**Comment by leixinstar** [comment]
your code can work ok。
my code is:
Glide.with(context)
				.load(realUrl)
				.centerCrop()
				.placeholder(R.drawable.default_avatar)
				.error(R.drawable.default_avatar)
				.diskCacheStrategy(DiskCacheStrategy.ALL)
				.bitmapTransform(new RoundedCornersTransformation(context,8,0))
				.into(imageView);

**Comment by squeeish** [comment]
@wasabeef from what I understand, we cannot use Glide's centerCrop() if we use bitmapTransform?

**Comment by wasabeef** [comment]
@leixinstar 
@squeeish 

Yeah..

It can't be used `centerCrop` if you use the `bitmapTransform`

**Comment by leixinstar** [comment]
RoundedCornersTransformation and CropTransformation(mContext, 300, 100, CropTransformation.CropType.TOP)，how can this two work together?

**Comment by balavishnu** [comment]
Removing centerCrop fixed the issue for me. Thanks

**Comment by TWiStErRob** [comment]
Check the code of `centerCrop`/`fitCenter`/`dontTransfrom/bitmapTransform` they all call `transform`. To combine two transformations you need to use the varargs version and forget about the convenience methods.

@wasabeef I think you should update https://github.com/wasabeef/glide-transformations#advanced-step-3 with the information that `.centerCrop()` in a combined usage becomes `new CenterCrop(context)` (similar for `fitCenter`.

**Comment by felipecsl** [comment]
@TWiStErRob that doesn't work either, same results

**Comment by felipecsl** [comment]
OK I was able to make it work by tweaking `RoundedCornersTransformation`. In the `transform()` method, you should use `outWidth` and `outHeight` instead of the source bitmap width/height

**Comment by TWiStErRob** [comment]
Sorry, I was wrong about `.transform(...)` I always forget that @wasabeef's transformations are `Transformation<Bitmap>` and not `BitmapTransformation`, using `.bitmapTransform(...)` works as expected, see https://github.com/wasabeef/glide-transformations/pull/40#issuecomment-218405816.

**Comment by qibin0506** [comment]
In Adapter, sometime it is ok, but sometime, not, my code : 
``` java
 if(opts.getRadius() != 0) {
            builder.bitmapTransform(new FitCenter(imageView.getContext()),
                    new RoundedCornersTransformation(imageView.getContext(),
                            opts.getRadius(), 0));
        }else {
            builder.bitmapTransform(new FitCenter(imageView.getContext()));
        }
```

**Comment by a1018875550** [comment]
how to slove this in V4 generate code?

**Comment by Allajah** [comment]
It works probably... (I'm writing with Kotlin)

```
class Utils {
    companion object {
        fun dip2px(context: Context, dp: Float): Int {
            val scale = context.resources.displayMetrics.density
            return (dp * scale + 0.5f).toInt()
        }
    }
}
```

```
val width = Utils.dip2px(ctx, 200.0f)
val height = Utils.dip2px(ctx, 200.0f)
Glide.with(ctx).load(imageUrl)
                .apply(overrideOf(width, height))
                .apply(bitmapTransform(MultiTransformation(CenterCrop(),
                        RoundedCornersTransformation(45, 0,
                                RoundedCornersTransformation.CornerType.ALL))))
                .into(imageView)
```

**Comment by KrackensCorp** [comment]
.apply(bitmapTransform(MultiTransformation(CenterCrop(), RoundedCorners(16,))))
