### ISSUE TITLE
BlurTransformation set centerCrop unused.

### ISSUE THREAD

**Issue by MarkMjw** [wasabeef/glide-transformations#17]
my code：
![qq 20150819171356](https://cloud.githubusercontent.com/assets/4126838/9352748/33d59b10-4696-11e5-8e06-ddebe55d817b.png)

and the effect：
![qq 20150819170851](https://cloud.githubusercontent.com/assets/4126838/9352757/40c3b55a-4696-11e5-8da4-828331633ec7.png)

**Comment by i906** [comment]
This worked for me:

```
BitmapPool pool = Glide.get(mBannerView.getContext()).getBitmapPool();

Glide.with(mBannerView.getContext())
        .load(event.getBanner())
        .bitmapTransform(new CenterCrop(pool), new GrayscaleTransformation(pool))
        .crossFade()
        .placeholder(R.drawable.bg_gray)
        .into(mBannerView);
```

Instead of using ```.centerCrop()```, I used like above.

**Comment by wasabeef** [comment]
@i906 
thanks.

**Comment by MarkMjw** [comment]
@i906 thanks!
and i has solved this problem with:
```java
  Glide.with(getActivity())
                    .load(user.image)
                    .placeholder(R.drawable.unlogin_cover)
                    .bitmapTransform(new BlurTransformation(getActivity(), pool), new CropTransformation(pool, width, height))
                    .into(mHeaderHolder.mCover);
```

**Comment by HappyDr0id** [comment]
Personally, I still consider that the issue is not fixed. The CenterCrop transformation is a tweak to do what the library should do from the beginning : respect the initial layout conditions.
