### ISSUE TITLE
Transformations should use the provided BitmapPool

### ISSUE THREAD

**Issue by sjudd** [wasabeef/glide-transformations#2]
In many cases Bitmaps can be obtained from or returned to the BitmapPool rather than being allocated or recycled. Doing so will reduce garbage collections and improve scrolling smoothness.

**Comment by wasabeef** [comment]
Hi. 
What would be the best thing to do?

thanks.

**Comment by sjudd** [comment]
Usually when you call ``Bitmap.createBitmap(width, height, config)`` you can instead run:

```java
Bitmap bitmap = bitmapPool.get(width, height, config);
if (bitmap == null) {
    bitmap = Bitmap.createBitmap(width, height, config);
}
```

And when you call ``bitmap.recycle()``, you can instead run:

```java
if (!bitmapPool.put(bitmap)) {
    bitmapPool.recycle()
}
```

Ideally you'd never call ``Bitmap.createBitmap`` unless you get a null result from the BitmapPool. You can find some more info on [Glide's wiki][1]. The [BitmapPool][2] docs may also be helpful.

[1]: https://github.com/bumptech/glide/wiki/Transformations#bitmap-re-use
[2]: http://bumptech.github.io/glide/javadocs/latest/com/bumptech/glide/load/engine/bitmap_recycle/BitmapPool.html

**Comment by wasabeef** [comment]
Thank you for your advice.
I will a try it in the next version.  :+1:
