### ISSUE TITLE
Duplicate files copied in APK lib/x86/librsjni.so

### ISSUE THREAD

**Issue by wangpeiyuan** [wasabeef/glide-transformations#26]
Error:Execution failed for task ':App:packageDebug'.

> Duplicate files copied in APK lib/x86/librsjni.so
>     File 1: /Users/admin/workspace/myapp/App/build/intermediates/exploded-aar/jp.wasabeef/glide-transformations/1.3.1/jni/x86/librsjni.so
>     File 2: /Users/admin/Library/Android/sdk/build-tools/21.1.2/renderscript/lib/packaged/x86/librsjni.so

**Comment by wasabeef** [comment]
@cock-tail 

see https://github.com/wasabeef/glide-transformations/issues/24

> What is the version of `Android Plugin for Gradle`?
> Please be on 1.5.0 or later.

> ```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.5.0'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}
> ```

**Comment by cock-tail** [comment]
Thanks.If i set 1.5.0 version it will cause other library problem

**Comment by wasabeef** [comment]
@cock-tail 

Sorry..

Fix. 2.0.0
