### ISSUE TITLE
Glide 4.0 breaks glide-transformations

### ISSUE THREAD

**Issue by pokowaka** [wasabeef/glide-transformations#27]
Change https://github.com/bumptech/glide/commit/2f053e67c728367bce8b6682b305f71709e3c8c6 breaks this library.

**Comment by wasabeef** [comment]
@pokowaka 

Thank you.

I will support it. :+1:

**Comment by pokowaka** [comment]
Opening up a pull request for you now.

**Comment by TWiStErRob** [comment]
Hmm, that's interesting. Careful not to break compatibility with v3, because v4's API is not even finalized yet.
