### ISSUE TITLE
How to specify border color and border width on CropCircleTransformation 

### ISSUE THREAD

**Issue by wanclem** [wasabeef/glide-transformations#30]
Hey there,nice job.Can you add support for specifying Transformation border widths and border colors? Thanks

**Comment by TWiStErRob** [comment]
It's not supported (yet?), take a look at #12 for a workaround (backround drawable containing a circle).

**Comment by charleston10** [comment]
@TWiStErRob worked with margin, with padding don't work.. It's a bit confusing, it should also work..
But thanks by your help

**Comment by TWiStErRob** [comment]
@charleston10 padding is on the background, not the image view; it's a little bit bigger circle as a drawable so it looks like a circular border.
