### ISSUE TITLE
CenterCrop and Blur Transformation

### ISSUE THREAD

**Issue by sourabhv** [wasabeef/glide-transformations#32]
The following code doesn't work, the image is not centercropped 

```
Glide.with(context)
    .load(url)
    .centerCrop()
    .bitmapTransform(new BlurTransformation(context))
    .into(image);
```

and this doesn't apply the transformation

```
Glide.with(context)
    .load(url)
    .bitmapTransform(new BlurTransformation(context))
    .centerCrop()
    .into(image);
```

**Comment by TWiStErRob** [comment]
Look into `.centerCrop`... they both call `.transform` so if you want a combination:
```java
.bitmapTransform(new CenterCrop(context), new BlurTransformation(context))
```

**Comment by rexih** [comment]
i'd like to encapsulate the codes twice to use Glide .here is my problem ,i'd like to use a List to save the transforms,but when i really invoke the method " bitmapTransform(			Transformation... bitmapTransformations) ",i don't know how to convert List to match the parameters。Could  u add a method with List parameter like "bitmapTransform(			List<Transformation> bitmapTransformations)"

**Comment by TWiStErRob** [comment]
@rexih use Glide's built-in `MultiTransformation` that has a `Collection` constructor. That gets created anyway automatically if you look into how `bitmapTransform`/`transform` works (`GenericRequestBuilder.transform`).

**Comment by rexih** [comment]
@TWiStErRob thx for the response. i looked into the code ,saw bitmapTransform use GifBitmapWrapperTransformation to handle the transforms and save the Transformation as a member(where use the MultiTransformation)
but i still dont know how to use MultiTransformation in builder. maybe later i will override a method

**Comment by TWiStErRob** [comment]
@rexih
```java
List<Transformation<Bitmap>> transforms = new LinkedList<>();
transforms.add(new CenterCrop(context));
if (blah)
    transforms.add(new BlurTransformation(context));

// ....bitmapTransform(transforms) // is what you want, but it doesn't exist

@SuppressWarnings("rawtypes") // to prevent a generic varargs warning later
MultiTransformation transformation = new MultiTransformation<Bitmap>(transforms);

....bitmapTransform(transformation) // this works
```

**Comment by rexih** [comment]
@TWiStErRob wow ,nice code!i misuderstood it.thx a lot!

**Comment by gargmeha** [comment]
@TWiStErRob , I have been looking into MultipleTransform. I have a requirement where I want to combine rotation animation while performing multipleTransformation. So, I have an image with RoundedCorner which I load using Glide. Then, if I tap on the image, it should basically crop the corners till it get rounded and rotate at the same time, while transformation is in progress. Based on above example, I tried to combine RoundedCornersTransformation and I pass in different radius as a parameter. Then, once the radius is equal to the width/2, it should call CropCircleTransformation. Visually, I only see CropCircleTransformation with rotation animation and what I want to see is square cropping the corners, converting into a circle with rotation. 

Here is my code snippet. 
My Image size is 156dpx156dp. I also looked at this issue
https://github.com/wasabeef/glide-transformations/issues/16 and still cannot make it work.

`    private void multipleTransformation(String imageUrl, ImageView imageView){
        List<Transformation<Bitmap>> transforms = new LinkedList<>();
        transforms.add(new RoundedCornersTransformation(mContext, 110, 0, RoundedCornersTransformation.CornerType.ALL));

        transforms.add(new RoundedCornersTransformation(mContext, 90, 0, RoundedCornersTransformation.CornerType.ALL));
        transforms.add(new RoundedCornersTransformation(mContext, 80, 0, RoundedCornersTransformation.CornerType.ALL));
        transforms.add(new RoundedCornersTransformation(mContext, 78, 0, RoundedCornersTransformation.CornerType.ALL));
        transforms.add(new CropCircleTransformation(mContext));
        MultiTransformation transformation = new MultiTransformation<Bitmap>(transforms);

        final float ROTATE_FROM = 0.0f;
        final float ROTATE_TO =  358.0f;
        RotateAnimation r; // = new RotateAnimation(ROTATE_FROM, ROTATE_TO);
        r = new RotateAnimation(ROTATE_FROM, ROTATE_TO, Animation.RELATIVE_TO_SELF, 0.5f, Animation.RELATIVE_TO_SELF, 0.5f);
        r.setDuration((long) 2*1500);
        r.setRepeatCount(3);
        r.setInterpolator(new LinearInterpolator());
        r.setRepeatMode(Animation.RESTART);

        Glide.with(mContext)
                .load(imageUrl)
                .bitmapTransform(transformation) 
                .animate(r)
                .into(imageView);
    }`

**Comment by TWiStErRob** [comment]
@gargmeha That's a really unrelated question to this issue... anyway, all transformations are applied before any animation starts. Applying multiple similar transformations this way just wastes resources, because it just creates new and new bitmaps, but in the end, the result will be just a circle crop. Animations are for revealing the image. Glide doesn't support what you want out of the box as far as I know.
