### ISSUE TITLE
Image is not transforming

### ISSUE THREAD

**Issue by vavan4567** [wasabeef/glide-transformations#33]
Hi, maybe I'm doing something wrong, but with big image the lib is not working.
    Bitmap bitmap = Glide.with(CropActivity.this)
                                          .load(mImageUri)
                                          .asBitmap()
                                          .transform(new SketchFilterTransformation(CropActivity.this))
                                          .fitCenter()
                                          .into(size, size)
                                          .get();
when I am trying to load small size picture it works. But with big one it just return original image

**Comment by bojancv** [comment]
Take a look at https://github.com/wasabeef/glide-transformations/issues/16 and https://github.com/wasabeef/glide-transformations/issues/32.

.fitCenter is calling transform also so you should combine your transformation like in the given example: .bitmapTransform(new CenterCrop(context), new BlurTransformation(context))

**Comment by HimanshuNarang** [comment]
Can i make a Custom Transformation by not extending BitmapTransformation?
