### ISSUE TITLE
How transform placeholder?

### ISSUE THREAD

**Issue by saulIHS** [wasabeef/glide-transformations#39]
bitmapTransform only edits the image into "load" not "placeholder", Is there a way to transform the placeholder?

**Comment by naturs** [comment]
```java
DrawableRequestBuilder<Integer> thumbnail = Glide.with(context)
                        .load(R.drawable.placeholder)
                        .bitmapTransform(new Transform());

Glide.with(context)
                        .load(url)
                        .bitmapTransform(new Transform())
                        .thumbnail(thumbnail)
                        .into(view);                
```
you can try this.

**Comment by proud2008** [comment]
glide4.0  找不到 DrawableRequestBuilder

**Comment by Thanvandh** [comment]
> glide4.0 找不到 DrawableRequestBuilder

Use This for 4.0

`        Transformation transformation = new RoundedCornersTransformation(context, Utils.dpToPx(5), Utils.dpToPx(5));

        RequestOptions requestOptions = new RequestOptions()
                .centerCrop()
                .transforms(transformation);

        RequestBuilder<Drawable> thumbnail = Glide.with(context)
                .load(R.drawable.placeholder_large)
                .apply(requestOptions);;
        Glide
                .with(convertView)
                .load(ApiClient.URL_BANNER + itemList.get(listPosition).getImage())
                .apply(requestOptions)
                .thumbnail(new RequestBuilder[]{thumbnail})
                .into(viewTarget);`
