### ISSUE TITLE
Strange Behavior when I'm using RoundedCornersTransformation in RecyclerView

### ISSUE THREAD

**Issue by IRMobydick** [wasabeef/glide-transformations#41]
Hi there
I've an issue with `RoundedCornersTransformation` transformation. As you can see in image below, when I applied rounded transformation to my image, image repeated in top corners:

![screenshot_2016-05-12-09-23-29](https://cloud.githubusercontent.com/assets/4468890/15204642/bf27d27c-1824-11e6-8268-652bf8a8efc2.png)

My code

```
            glide.load(url)
                .priority(Priority.IMMEDIATE)
                .override(width, height)
                .diskCacheStrategy(DiskCacheStrategy.RESULT)
                .skipMemoryCache(true)
                .priority(Priority.IMMEDIATE)
                .bitmapTransform(new RoundedCornersTransformation(this.image.getContext(), AndroidUtilities.dpToPx(6, this.image.getContext()), 0, RoundedCornersTransformation.CornerType.TOP))
                .into(this.image);
```

**Comment by TWiStErRob** [comment]
I checked the sources and it looks ok to me. I tried it too and it worked fine.
Are you sure you don't have two ImageViews or an ImageView and a background loaded?
Try to clear the disk cache, though the transformation has a proper id, so it should evict previous versions.

**Comment by IRMobydick** [comment]
No I have not any more `ImageView` in my View:

        <android.support.percent.PercentFrameLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:clickable="true"
                android:focusable="true" >

                <ProgressBar
                    android:id="@+id/progress"
                    android:layout_width="24dp"
                    android:layout_height="24dp"
                    android:layout_gravity="center"
                    android:indeterminate="true" />

                <ImageView
                    android:id="@+id/image"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:layout_margin="0dp"
                    app:layout_aspectRatio="178%"
                    app:layout_widthPercent="100%"
                    android:adjustViewBounds="true"
                    android:contentDescription="@string/ds_post_image"
                    android:padding="0dp"
                    android:scaleType="centerCrop" />
                
        </android.support.percent.PercentFrameLayout>

It happened again :(

**Comment by TWiStErRob** [comment]
I tried with that layout and no change.

> It happened again :(

Does this mean that it doesn't always happen? What is your android version?

**Comment by jkj8790** [comment]
@TWiStErRob I have a same issue.

![screenshot_2016-05-23-16-23-54](https://cloud.githubusercontent.com/assets/5154440/15463459/a9c2334e-2104-11e6-9247-dee260e466f8.png)

Here's my code:
`        <RelativeLayout
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:background="@color/dark_grey">

          <ImageView
              android:id="@+id/img_cover"
              android:layout_width="wrap_content"
              android:layout_height="wrap_content"
              android:layout_centerHorizontal="true"
              android:background="#f00"
              />

          <ProgressBar
              android:id="@+id/progress"
              android:layout_width="wrap_content"
              android:layout_height="wrap_content"
              android:layout_centerInParent="true"
              android:visibility="gone"/>

          <View
              android:id="@+id/recent_selector"
              android:layout_width="match_parent"
              android:layout_height="match_parent"
              android:background="@drawable/selector_recent_cover"
              tools:visibility="gone"/>
        </RelativeLayout>
`

And here is my layout:
`        <RelativeLayout
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:background="@color/dark_grey">

          <ImageView
              android:id="@+id/img_cover"
              android:layout_width="wrap_content"
              android:layout_height="wrap_content"
              android:layout_centerHorizontal="true"
              android:background="#f00"
              />

          <ProgressBar
              android:id="@+id/progress"
              android:layout_width="wrap_content"
              android:layout_height="wrap_content"
              android:layout_centerInParent="true"
              android:visibility="gone"/>

          <View
              android:id="@+id/recent_selector"
              android:layout_width="match_parent"
              android:layout_height="match_parent"
              android:background="@drawable/selector_recent_cover"
              tools:visibility="gone"/>
        </RelativeLayout>
`

It only occurs when CornerType is top. 
I saw this bug in android version 4.4.2, 5.0.2
It's working in 6.0.1

**Comment by TWiStErRob** [comment]
Those version numbers suggest that it may have to do with drawing on a canvas in different versions of Android. @was a beef did you look into this yet?

**Comment by YuckFo** [comment]
Same problem here, but it occurs everytime i specify CornerType. For example here is result for code 

> Glide.with(getContext())
> 									.load(http://... .png)
> 																.skipMemoryCache(true)
> 									.bitmapTransform(new RoundedCornersTransformation(getContext(), (int) getContext().getResources().getDimension(R.dimen.voucher_corners_radius), 0, RoundedCornersTransformation.CornerType.OTHER_TOP_LEFT))
> 									.into(Image);


![other_top_bottom](https://cloud.githubusercontent.com/assets/9945659/19235831/664f7082-8ef4-11e6-8826-7cf62e7d0fc2.png)

**Comment by AhmedGamal-Inmobly** [comment]
@IRMobydick 
Any solution here, having the same issue ?
