### ISSUE TITLE
Strange behaviour in RecyclerView when Using "TopCrop" transformation

### ISSUE THREAD

**Issue by ndorigatti** [wasabeef/glide-transformations#42]
I'm using the transformation:
https://github.com/wasabeef/glide-transformations/blob/master/transformations%2Fsrc%2Fmain%2Fjava%2Fjp%2Fwasabeef%2Fglide%2Ftransformations%2FCropTransformation.java

to show only the 80% of an image from the top (i want to fit the width and use the 80% of the picture height to be shown). Obviously cropCenter,fitCenter etc do not help, but this class seems so.

If I have a custom activity with two elements everythings runs fine, but when I do use in my code with recycler view, strange issues appears.
I do use glide to read a png from cache folder (no network) in the adapter (onBindView):

``` java
final int measuredWidth = viewHolder.getThumbImageView().getMeasuredWidth();

   if (tmpIssue.isDownloaded()) {
//Show the image
            File destFile = new File(statusView.getContext().getCacheDir(), tmpIssue.getName() + FileUtils.FILE_EXTENSION_PNG);
            Glide.with(statusView.getContext().getApplicationContext())
                    .load(destFile)
                    .signature(new StringSignature(FileUtils.getSha1(destFile)))                  
                    .bitmapTransform(new CropTransform(statusView.getContext().getApplicationContext(),
                                    measuredWidth,
                                    viewHolder.getThumbImageView().getMaxHeight(), CropTransform.CropType.TOP))
                 .placeholder(R.drawable.preview_bw).error(R.drawable.preview_bw).diskCacheStrategy(DiskCacheStrategy.NONE)
                    .into(viewHolder.getThumbImageView());
        } else {
            //show the placeholder
            Glide.with(statusView.getContext().getApplicationContext())
                    .load(R.drawable.preview_bw)
                    .bitmapTransform(new CropTransform(statusView.getContext().getApplicationContext(),
                            measuredWidth,
                            viewHolder.getThumbImageView().getMaxHeight(), CropTransform.CropType.TOP))
                    .placeholder(R.drawable.preview_bw).error(R.drawable.preview_bw).diskCacheStrategy(DiskCacheStrategy.NONE)
                    .into(viewHolder.getThumbImageView());
        }
```

and i do think it is something with view recycling.. am i Right? 
Attached the result:
top two elements have a preview file and are loaded badly (no text and image takes also the white space), lower left is ok, that's the desired behaviour, lower right is an element with no preview, so it is using the "else" of the above code, loading from drawable resources...

The transform class is the one in this repo, no modifications at all

![device-2016-05-16-221124](https://cloud.githubusercontent.com/assets/3414365/15302421/2fd9f374-1bb3-11e6-8340-ad590489252e.png)

**Comment by DanielWorld** [comment]
You gotta resize imageview with specific width, height first, then use Glide.Bitmaptransform with that specific width, height then it will work!

**Comment by ndorigatti** [comment]
Yes, thanks for the answer. I did some more research and found out that i was wrongly assuming glide adapt image view to the picture! I used 'listener' and when resource is ready I recalculate and set image view sizes, now works very well!
