### ISSUE TITLE
Out of Memory

### ISSUE THREAD

**Issue by DanielWorld** [wasabeef/glide-transformations#43]
when it loads image using recyclerView, it causes out of memory. Need to solve this

**Comment by sunxu3074** [comment]
@DanielWorld Are you solved it ? I meet this problem also .

**Comment by kuoliangkwong** [comment]
I'm having the same problem when using ToonFilterTransformation.

`java.lang.OutOfMemoryError: Failed to allocate a 48771084 byte allocation with 16777120 free bytes and 17MB until OOM`

My image is large image with 3.56MB. Is there any way we can add filter to large image?

**Comment by kuoliangkwong** [comment]
I added android:largeHeap and it seems to work fine.
