### ISSUE TITLE
The sizes of the corner for the Image are different

### ISSUE THREAD

**Issue by AndSync** [wasabeef/glide-transformations#47]
ImageView in xml are all like this
                <ImageView
                    android:id="@+id/iv_pic_three"
                    android:layout_width="match_parent"
                    android:layout_height="75dp"
                    android:scaleType="fitXY"/>

```
public static void loadCornerImage(final Context context, String url, final ImageView imageView) {
    Glide.with(context).load(url).placeholder(R.mipmap.list_pic_loading).bitmapTransform(new RoundedCornersTransformation(context, 10, 0)
    ).diskCacheStrategy(DiskCacheStrategy.SOURCE).into(imageView);
}
```

![qq 20160625120218](https://cloud.githubusercontent.com/assets/5254869/16354631/b471c20a-3acc-11e6-96b7-e8194687487d.png)

**Comment by lph2012** [comment]
我也遇到了同样的问题，请问你是怎么解决的

**Comment by TWiStErRob** [comment]
Using a custom transformation removes Glide's ability to auto-apply fitCenter/centerCrop so you need to help it out:
```java
.bitmapTransform(new FitCenter(context), new RoundedCornersTransformation(context, 10, 0))
```
this will make image Bitmaps uniform in pixel size and hence the corners should have the same size.

**Comment by MrLaird** [comment]
@AndSync have you sovled this problem,and how to solve it?please tell me , thanks.

**Comment by AndSync** [comment]
@MrLaird I have not solve it,because the dedign for our app is changed. you can try the method by TWiStErRob answered  upstairs

**Comment by MrLaird** [comment]
@AndSync I try  the method by @TWiStErRob  answered,but  it work not very well.
![image](https://cloud.githubusercontent.com/assets/8874054/24029525/bdcead48-0b11-11e7-8ab3-a7aaada4f9fe.png)

**Comment by MrLaird** [comment]
@AndSync @TWiStErRob my code is here:
![image](https://cloud.githubusercontent.com/assets/8874054/24029538/f9ee265a-0b11-11e7-9cf3-b9d9fdafcc8e.png)

**Comment by TWiStErRob** [comment]
@MrLaird I don't see any difference in corner size, the lines of the right image may be deceiving to the eye:
![image](https://cloud.githubusercontent.com/assets/2906988/24062458/84534c08-0b53-11e7-8912-b7ec0538a1b9.png)
(created this by removing background, and flipping the right to the left image, and changing its transparency; the grey pixels are residue from imperfect background cutting)
