### ISSUE TITLE
Using CropTransform gives a black background

### ISSUE THREAD

**Issue by AkshayChordiya** [wasabeef/glide-transformations#5]
Hi,

Thank you for providing excellent transformations. And I'm using ```CropCircleTransformation``` & getting cool Circular images but I'm also getting weird black background to it. I hope you can help me fix it.

**Comment by wasabeef** [comment]
@AkshayChordiya 

Hi.
Do you use the `PREFER_ARGB_8888`?

Take a look at this.
https://github.com/bumptech/glide/wiki/Configuration#bitmap-format

**Comment by AkshayChordiya** [comment]
@wasabeef 
Yeah it worked.
