### ISSUE TITLE
RoundedCornersTransformation cannot RoundedCorners network image

### ISSUE THREAD

**Issue by tianqing2117** [wasabeef/glide-transformations#52]
RoundedCornersTransformation cannot RoundedCorners network image？
I do
 Glide.with(mContext)
                .load(url)
                .bitmapTransform(new RoundedCornersTransformation(mContext, radius, 0))
                .crossFade()
                .into(imageView);

but do not have any effect。

**Comment by tianqing2117** [comment]
I find that I set the ImageView   android:scaleType="centerCrop"  in  xml.So the roundedCorners could not display.

**Comment by yanxinmiao** [comment]
me too ,who give me some advances ?

**Comment by YuckFo** [comment]
remove centercrop from xml and add it to bitmapTransform
.bitmapTransform(new CenterCrop(mContext),new RoundedCornersTransformation(mContext, radius, 0))
