### ISSUE TITLE
scaleType conflict with MaskTransformation

### ISSUE THREAD

**Issue by promisenxu** [wasabeef/glide-transformations#54]
Thanks for the great library!

I am using the MaskTransformation and noticed that if scaleType was set (in my case, to center), the MaskTransformation would have no effect.

This wouldn't impact my use case but wondering why it would be like this.

Thanks.

**Comment by AnyTT** [comment]
https://github.com/wasabeef/glide-transformations/issues/52
-->@YuckFo :

remove centercrop from xml and add it to bitmapTransform
.bitmapTransform(new CenterCrop(mContext),new RoundedCornersTransformation(mContext, radius, 0))
