### ISSUE TITLE
How to Crop images to Aspect ratio

### ISSUE THREAD

**Issue by CeJienAJPC** [wasabeef/glide-transformations#55]
The square transformation lets you crop the image to an aspect ratio of 1:1. However, what if I want to crop the image to other aspect ratios like 16:9, 16:8 and so on. Is there any way I can achieve this using this library?

Regards

**Comment by rayworks** [comment]
@CeJienAJPC 
Maybe you can have a look at sample code in this [gist](https://gist.github.com/rayworks/ce933efc201ba6c5c8f001b658e26ca0)
