### ISSUE TITLE
RoundedCornersTransformation radius applied on image source size

### ISSUE THREAD

**Issue by gradha** [wasabeef/glide-transformations#56]
When I apply the rounded corner transformation I have different visual results with the same radius input. In the following screenshot you can see two images using the same corner radius, however one has a bigger visual effect because its source size is smaller, and the image is scaled to match the area.

![2016-10-16 00 37 58](https://cloud.githubusercontent.com/assets/101927/19414361/d41c5706-934a-11e6-9af8-7e12ffecd59f.png)

Is there any way to tell the `RoundedCornersTransformation` to apply the radius on the destination view size rather than on the source? I think this might be related to #47 though I don't understand what's being said there.

**Comment by TWiStErRob** [comment]
Check #47 again, I answered there.

**Comment by gradha** [comment]
That didn't help me, ended up scaling the radius for the corner.
