### ISSUE TITLE
Transparency issue

### ISSUE THREAD

**Issue by naixx** [wasabeef/glide-transformations#6]
In the source bitmap doesn't support transparency, the resulted transformed bitmap will have black borders due to original config.
```java
Bitmap.Config config = source.getConfig() != null ? source.getConfig() : Bitmap.Config.ARGB_8888;
```
Taken from circle transformation.

Is that desired behaviour for transformed images?

**Comment by wasabeef** [comment]
@naixx 
Is it the same problem?
https://github.com/wasabeef/glide-transformations/issues/5

**Comment by wasabeef** [comment]
@naixx 

Hi

pushed v.1.0.5
use ARGB_8888 :+1:

**Comment by naixx** [comment]
Great! Thank you! :+1:
