### ISSUE TITLE
Issue with conforming to layout params. Transform has mind of its own

### ISSUE THREAD

**Issue by eric-townsquared** [wasabeef/glide-transformations#62]
I specify width and height that I want my imageview to be, and somewhere along the way, the transformation overwrites it.

I primarily only want rounded corners. my images can come down from the network in any aspect ratio, and my imageview is supposed to be a landscape rectangle (with rounded corners), with the bitmap set to centerCrop scaleType. So I'd like the transform not to do anything to that. Thoughts?

**Comment by okacat** [comment]
Have you tried the solution in issue #32 ? Instead of calling `.centerCrop()` add `new CenterCrop()` inside of your `.bitmapTransform(...)`.
