### ISSUE TITLE
in glide 4.0, RoundedCornersTransformation need implement  method updateDiskCacheKey

### ISSUE THREAD

**Issue by SureCoder** [wasabeef/glide-transformations#73]
**in glide 4.0, RoundedCornersTransformation need implement method updateDiskCacheKey.**
Exception like this:
 java.lang.AbstractMethodError: abstract method "void com.bumptech.glide.load.Key.updateDiskCacheKey(java.security.MessageDigest)"

**Comment by SureCoder** [comment]
Thanks to the author's library.
This problem can be solved like this:
We can copy RoundedCornersTransformation all code move to your package.
**Than override updateDiskCacheKey method like this:**
**@Override
    public void updateDiskCacheKey(MessageDigest messageDigest) {
         //do nothing
    }**
**and copy the original code into the new transform method.**
It's work for me.

**Comment by guoleifei** [comment]
RequestOptions options = new RequestOptions();
        options.centerCrop().transform(new RoundedCorners(round));
        Glide.with(context).load(url).apply(options).into(imageView);

你可以用glide 自带的实现圆角

**Comment by tianqiujie** [comment]
@guoleifei  多谢 解决了

**Comment by S-Co** [comment]
@guoleifei 
   Glide.with(this).load(music.getCoverPath()) .bitmapTransform(new BlurTransformation(this, 25, 2), new CenterCrop(this)).placeholder(R.drawable.play_page_default_bg).error(R.drawable.play_page_default_bg).override(300, 300).into(mIvPlayPageBgActivityPlay);
我这种毛玻璃效果怎么替换

**Comment by guoleifei** [comment]
-- 内置的方法没有毛玻璃的 你应该看下楼主的。方法

**Comment by iamzhengkai** [comment]
@S-Co 

package com.kevin.glidetest;

import android.content.Context;
import android.graphics.Bitmap;
import android.graphics.Canvas;
import android.graphics.Paint;
import android.os.Build;
import android.renderscript.RSRuntimeException;
import android.support.annotation.NonNull;

import com.bumptech.glide.Glide;
import com.bumptech.glide.load.engine.bitmap_recycle.BitmapPool;
import com.bumptech.glide.load.resource.bitmap.BitmapTransformation;

import java.nio.charset.Charset;
import java.security.MessageDigest;

/**
 * Function:
 *
 * @FileName: com.kevin.glidetest.BlurTransformation.java
 * @author: zk
 * @date: 2017-08-11 22:37
 */

public class BlurTransformation extends BitmapTransformation {

    private static String STRING_CHARSET_NAME = "UTF-8";
    private static final String ID = "com.kevin.glidetest.BlurTransformation";
    private static Charset CHARSET = Charset.forName(STRING_CHARSET_NAME);
    private static final byte[] ID_BYTES = ID.getBytes(CHARSET);

    private static int MAX_RADIUS = 25;
    private static int DEFAULT_DOWN_SAMPLING = 1;

    private Context mContext;
    private BitmapPool mBitmapPool;

    private int mRadius;
    private int mSampling;

    public BlurTransformation(Context context) {
        this(context, Glide.get(context).getBitmapPool(), MAX_RADIUS, DEFAULT_DOWN_SAMPLING);
    }

    public BlurTransformation(Context context, BitmapPool pool) {
        this(context, pool, MAX_RADIUS, DEFAULT_DOWN_SAMPLING);
    }

    public BlurTransformation(Context context, BitmapPool pool, int radius) {
        this(context, pool, radius, DEFAULT_DOWN_SAMPLING);
    }

    public BlurTransformation(Context context, int radius) {
        this(context, Glide.get(context).getBitmapPool(), radius, DEFAULT_DOWN_SAMPLING);
    }

    public BlurTransformation(Context context, int radius, int sampling) {
        this(context, Glide.get(context).getBitmapPool(), radius, sampling);
    }

    public BlurTransformation(Context context, BitmapPool pool, int radius, int sampling) {
        mContext = context.getApplicationContext();
        mBitmapPool = pool;
        mRadius = radius;
        mSampling = sampling;
    }



    @Override
    protected Bitmap transform(@NonNull BitmapPool pool, @NonNull Bitmap toTransform, int
            outWidth, int outHeight) {
        Bitmap source = toTransform;

        int width = source.getWidth();
        int height = source.getHeight();
        int scaledWidth = width / mSampling;
        int scaledHeight = height / mSampling;

        Bitmap bitmap = mBitmapPool.get(scaledWidth, scaledHeight, Bitmap.Config.ARGB_8888);
        if (bitmap == null) {
            bitmap = Bitmap.createBitmap(scaledWidth, scaledHeight, Bitmap.Config.ARGB_8888);
        }

        Canvas canvas = new Canvas(bitmap);
        canvas.scale(1 / (float) mSampling, 1 / (float) mSampling);
        Paint paint = new Paint();
        paint.setFlags(Paint.FILTER_BITMAP_FLAG);
        canvas.drawBitmap(source, 0, 0, paint);

        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR2) {
            try {
                bitmap = RSBlur.blur(mContext, bitmap, mRadius);
            } catch (RSRuntimeException e) {
                bitmap = FastBlur.blur(bitmap, mRadius, true);
            }
        } else {
            bitmap = FastBlur.blur(bitmap, mRadius, true);
        }

//        return BitmapResource.obtain(bitmap, mBitmapPool);
        return bitmap;
    }

    @Override
    public int hashCode() {
        return ID.hashCode();
    }

    @Override
    public boolean equals(Object obj) {
        return obj instanceof BlurTransformation;
    }

    @Override
    public void updateDiskCacheKey(MessageDigest messageDigest) {
        messageDigest.update(ID_BYTES);
    }
}

**Comment by iielse** [comment]
![image](https://user-images.githubusercontent.com/7521943/29307664-5fd6294c-81d5-11e7-9870-46fe7f64da19.png)

@guoleifei 
就上面圆角，下面直角 怎么破

**Comment by guoleifei** [comment]
@iielse 你需要看下他哪个怎么写的 就是哪个圆角的 然后只设置上边的圆角--

**Comment by JSnail** [comment]
请问在glide4.0上怎么实现模糊效果？

**Comment by wasabeef** [comment]
I just released glide-transformations 3.0.0. So could you check that?

**Comment by iamzhengkai** [comment]
@iielse  可以参考：http://blog.csdn.net/qiushi_1990/article/details/53188554
