### ISSUE TITLE
Glide 4.0 stable released

### ISSUE THREAD

**Issue by b95505017** [wasabeef/glide-transformations#77]
https://github.com/bumptech/glide/releases/tag/v4.0.0
I think that this library should be updated to avoid copying out and modify each class manually.

**Comment by Dahnark** [comment]
Up

**Comment by wasabeef** [comment]
@b95505017 
@Dahnark 

Ok, Thanks
Just now, I'm preparing that. So I'll release the new version for 4.0.0 next week.

**Comment by Dahnark** [comment]
@wasabeef thank you :D

**Comment by wasabeef** [comment]
@b95505017 @Dahnark 
I just released glide-transformations 3.0.0. So could you check that?

**Comment by Dahnark** [comment]
This should work with glide 3 too?
