### ISSUE TITLE
How to get the tranformed image ?

### ISSUE THREAD

**Issue by Arkar-Aung** [wasabeef/glide-transformations#8]
I want to get transformed image to upload to server. To get this, I think I have to write file with that transformed bitmap on storage. Is it the best way to do it with this library or is there any other ways ?

**Comment by wasabeef** [comment]
Hi.

this?
https://github.com/bumptech/glide/wiki/Loading-and-Caching-on-Background-Threads#into

```java
Bitmap myBitmap = Glide.with(applicationContext)
    .load(yourUrl) 
    .asBitmap() 
    .centerCrop() 
    .into(500, 500) 
    .get() 
```

**Comment by Arkar-Aung** [comment]
Thanks !!  It's useful for me !!
