### ISSUE TITLE
Adding a border to the crop transformations

### ISSUE THREAD

**Issue by vpratfr** [wasabeef/glide-transformations#80]
Would be nice if the transformations dealing with Crop could also add a border around the resulting shape (with customizable thickness and color)

**Comment by Rainer-Lang** [comment]
@vpratfr Absolutely!

**Comment by yuzhentao** [comment]
<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android"
    android:shape="rectangle">

    <corners android:radius="12dp" />
    <stroke
        android:width="1dp"
        android:color="@color/new_gray_4" />

</shape>

<ImageView
            android:layout_width="56dp"
            android:layout_height="56dp"
            android:background="@drawable/bg_test"
            android:padding="1.2dp" />

RequestOptions options = new RequestOptions();
options.centerCrop().transform(new RoundedCorners(DimensionUtil.dp2px(context, 12)));
Glide.with(context).load(url).apply(options).into(iv);

**Comment by yuzhentao** [comment]
<shape xmlns:android="http://schemas.android.com/apk/res/android"
    android:shape="rectangle">
    <corners android:radius="12dp" />
    <stroke
        android:width="1dp"
        android:color="@color/new_gray_4" />
</shape>

<ImageView
            android:layout_width="56dp"
            android:layout_height="56dp"
            android:background="@drawable/bg_test"
            android:padding="1.2dp" />

RequestOptions options = new RequestOptions();
options.centerCrop().transform(new RoundedCorners(DimensionUtil.dp2px(context, 12)));
Glide.with(context).load(url).apply(options).into(iv);

**Comment by yuzhentao** [comment]
```
<shape xmlns:android="http://schemas.android.com/apk/res/android"
    android:shape="rectangle">
    <corners android:radius="12dp" />
    <stroke
        android:width="1dp"
        android:color="@color/new_gray_4" />
</shape>
```

```
<ImageView
            android:layout_width="56dp"
            android:layout_height="56dp"
            android:background="@drawable/bg_test"
            android:padding="1.2dp" />
```

```
RequestOptions options = new RequestOptions();
options.centerCrop().transform(new RoundedCorners(DimensionUtil.dp2px(context, 12)));
Glide.with(context).load(url).apply(options).into(iv);
```

**Comment by Dahnark** [comment]
@yuzhentao can you give me more info about DimensionUtils?

**Comment by yuzhentao** [comment]
@Dahnark 
`    public static int dp2px(Context context, float dp) {
        final float scale = context.getResources().getDisplayMetrics().density;
        return (int) (dp * scale + 0.5F);
    }`

**Comment by yuzhentao** [comment]
@Dahnark 
    public static int dp2px(Context context, float dp) {
        final float scale = context.getResources().getDisplayMetrics().density;
        return (int) (dp * scale + 0.5F);
    }

**Comment by Rainer-Lang** [comment]
Is the border "cutting" the image, making it smaller?

**Comment by vpratfr** [comment]
That is not doing what I meant. 

I mean that if you crop in a star/circular/rectangular/etc. shape, you should be able to specify an optional border without having to add any extra drawable or so.

**Comment by daesu** [comment]
Bit late but if this helps anyone else. 

Just extend BitmapTransformation from Glide. Then add a method (see addBorderToCircularBitmap below) to create the border on the Bitmap. 

Note: The border method was taken from; https://android--examples.blogspot.kr/2015/11/android-circular-bitmap-with-border-and.html

```
public class CircleCropBorder extends BitmapTransformation {
    // The version of this transformation, incremented to correct an error in a previous version.
    // See #455.
    private static final int VERSION = 1;
    private static final String ID = "com.bumptech.glide.load.resource.bitmap.CircleCrop." + VERSION;
    private static final byte[] ID_BYTES = ID.getBytes(CHARSET);

    // Bitmap doesn't implement equals, so == and .equals are equivalent here.
    @SuppressWarnings("PMD.CompareObjectsWithEquals")
    @Override
    protected Bitmap transform(
            @NonNull BitmapPool pool, @NonNull Bitmap toTransform, int outWidth, int outHeight, int bColor, int bwidth) {
        Bitmap circle = TransformationUtils.circleCrop(pool, toTransform, outWidth, outHeight);
        Bitmap mBitmap = addBorderToCircularBitmap(circle, bWidth, bColor);
        return mBitmap;
    }

    @Override
    public boolean equals(Object o) {
        return o instanceof CircleCropBorder;
    }

    @Override
    public int hashCode() {
        return ID.hashCode();
    }

    @Override
    public void updateDiskCacheKey(@NonNull MessageDigest messageDigest) {
        messageDigest.update(ID_BYTES);
    }

    // Custom method to add a border around circular bitmap
    protected Bitmap addBorderToCircularBitmap(Bitmap srcBitmap, int borderWidth, int borderColor){
        // Calculate the circular bitmap width with border
        int dstBitmapWidth = srcBitmap.getWidth()+borderWidth*2;

        Bitmap dstBitmap = Bitmap.createBitmap(dstBitmapWidth,dstBitmapWidth, Bitmap.Config.ARGB_8888);

        Canvas canvas = new Canvas(dstBitmap);
        canvas.drawBitmap(srcBitmap, borderWidth, borderWidth, null);

        Paint paint = new Paint();
        paint.setColor(borderColor);
        paint.setStyle(Paint.Style.STROKE);
        paint.setStrokeWidth(borderWidth);
        paint.setAntiAlias(true);

        /*
            public void drawCircle (float cx, float cy, float radius, Paint paint)
                Draw the specified circle using the specified paint. If radius is <= 0, then nothing
                will be drawn. The circle will be filled or framed based on the Style in the paint.

            Parameters
                cx : The x-coordinate of the center of the cirle to be drawn
                cy : The y-coordinate of the center of the cirle to be drawn
                radius : The radius of the cirle to be drawn
                paint : The paint used to draw the circle
        */
        // Draw the circular border around circular bitmap
        canvas.drawCircle(
                canvas.getWidth() / 2, // cx
                canvas.getWidth() / 2, // cy
                canvas.getWidth()/2 - borderWidth / 2, // Radius
                paint // Paint
        );

        // Free the native object associated with this bitmap.
        srcBitmap.recycle();

        // Return the bordered circular bitmap
        return dstBitmap;
    }
}
```

**Comment by WrathChaos** [comment]
@yuzhentao  You're rock man! Thank you so much, saved so many hours.

**Comment by ypresto** [comment]
Note that `private static final String ID = "com.bumptech.glide.load.resource.bitmap.CircleCrop." + VERSION;` should be different value than original CircleCrop. Change it before using this.

**Comment by deathstroke007** [comment]
SVGs are not getting roundedcornered. Jpgs and Pngs are working fine.
