### ISSUE TITLE
proguard-rules.txt make Release Build Failed

### ISSUE THREAD

**Issue by liaoinstan** [wasabeef/glide-transformations#86]
IOException: proguard.ParseException: Unknown option '-keepresourcexmlelements' in line 11 of file '.../proguard-rules.txt'

your proguard-rules.txt
line 11: -keepresourcexmlelements manifest/application/meta-data@value=GlideModule

delete this line is ok
#-keepresourcexmlelements manifest/application/meta-data@value=GlideModule

**Comment by Dahnark** [comment]
I got this error too

**Comment by Dahnark** [comment]
How can I fix this? This proguard file is in cache folder

**Comment by wasabeef** [comment]
@liaoinstan 
@Dahnark 

I'm so sorry about that. So I released 3.0.1 for this problem just now.
Could you try new version?

**Comment by Dahnark** [comment]
Fixed for me @wasabeef

**Comment by yanxinmiao** [comment]
@wasabeef i get this error , but when delete this line ,  i  get  a new error:
```
Error:Execution failed for task ':app:transformClassesWithAndroidGradleClassShrinkerForAnzhiDebug'.
> java.lang.ArrayIndexOutOfBoundsException (no error message)
```
