### ISSUE TITLE
Strange behavior in Recyclerview when use transformation with glide 4.0+

### ISSUE THREAD

**Issue by asker517** [wasabeef/glide-transformations#93]
Hi, I use the codes just like below :
```
glideRequest.apply(new RequestOptions()
        .placeholder(placeholderRes())
      .transform(new RoundedCornersTransformation())
```
when adapter refresh item ,it will leads blinking between `placeHolder` & `loaded drawable` until all load finished.

I just compare with `RoundedCorners` in `Glide` , is it should override `hashCode()` & `equals()` method in transformation class ?

**Comment by CrabeMan** [comment]
Hi, same problem here.
I have strange blinking by using the RoundedCornersTransformation in a RecyclerView:
```
options = options.transform(new RoundedCornersTransformation(5, 0));
```

But no problem with
```
options.apply(RequestOptions.circleCropTransform())
```

CrabeMan.
