### ISSUE TITLE
RoundedCornersTransformation not working when use glide4.0

### ISSUE THREAD

**Issue by zhengfei** [wasabeef/glide-transformations#94]
when scaleType is centerCrop

**Comment by vadimgoroshevsky** [comment]
@zhengfei you can use Glide's `RoundedCorners` transformation. And please note that `centerCrop()` is overriding previous transformations. So you can use         GlideApp.with(context)
                .load(ImageTools.getImagePath(uri))
                //.diskCacheStrategy(DiskCacheStrategy.RESOURCE)
                //.transition(DrawableTransitionOptions.withCrossFade())
                .transforms(new CenterCrop(), new RoundedCorners(ResourceUtils.DPtoPX(5)))
                .into(imageView);

;

**Comment by Jungle68** [comment]
@vadimgoroshevsky this is not work

**Comment by a1018875550** [comment]
![qq20171207-180550](https://user-images.githubusercontent.com/8246218/33709738-4d5143e4-db79-11e7-96ae-2b82af2f0723.png)
it show error ,When I add 
```
.transforms(new CenterCrop(), new RoundedCorners(radius))
```

**Comment by sud007** [comment]
This is not working ! Any body to the rescue?

**Comment by Kerry50407** [comment]
@a1018875550  Try to use  .transform"s" not .transform

**Comment by ChampIsMe** [comment]
@vadimgoroshevsky your answer worked for me

**Comment by abbath0767** [comment]
However - why is this happening?

**Comment by Klay-11** [comment]
nice its work @vadimgoroshevsky

**Comment by blusewang** [comment]
wow! it work @vadimgoroshevsky great

**Comment by Thien658jjh** [comment]
It's not working
![image](https://user-images.githubusercontent.com/42166894/58687038-a8222600-83aa-11e9-9f8c-42f5ff3f960a.png)

**Comment by algrid** [comment]
Now that "transforms" is deprecated what should we use instead?

**Comment by algrid** [comment]
ah, it seems that ".transform(new CenterCrop(), new RoundedCorners(radius))" works just fine

**Comment by ishaan-khan** [comment]
> Now that "transforms" is deprecated what should we use instead?
 You can use RequestionOptions().transform() and utilize the MultiTransformation(tranformations..) to apply mutliple transformation
