### ISSUE TITLE
Software rendering doesn't support hardware bitmaps

### ISSUE THREAD

**Issue by LongAgoLong** [wasabeef/glide-transformations#95]
Software rendering doesn't support hardware bitmaps--when I use BlurTransformation in Android O.

**Comment by AndroidDeveloperLB** [comment]
I think you can use a workaround for this, by forcing Glide to always use ARGB_8888 instead of HARDWARE. 

```
public class GlideConfiguration extends AppGlideModule {

    @Override
    public void applyOptions(Context context, GlideBuilder builder) {
        // Apply options to the builder here.
        builder.setDefaultRequestOptions(
                new RequestOptions().format(DecodeFormat.PREFER_ARGB_8888));
    }

}

```

However, I don't know how to make the SDK use this, as I'm quite new to this. 

Can you please let me know how to use it?

This is how I use the image loading with the transformation:

      String url = "https://upload.wikimedia.org/wikipedia/commons/e/e0/Large_Scaled_Forest_Lizard.jpg";
      Glide.with(MainActivity.this).load(url).transition(new DrawableTransitionOptions().crossFade())
                        .apply(RequestOptions.bitmapTransform(new BlurTransformation(MainActivity.this,2)))
                        .into(mInternetImageView);

It should work, right?

**Comment by AndroidDeveloperLB** [comment]
@wasabeef Why close it? Do you have a solution of this issue?
How do you do it exactly?

**Comment by ksc91u** [comment]
@AndroidDeveloperLB  use DecodeFormat.DEFAULT on Android O

**Comment by AndroidDeveloperLB** [comment]
@ksc91u Can you please put a full snippet to this? You can use what I wrote if you wish.
