### ISSUE TITLE
Cannot import project and run its sample

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [wasabeef/glide-transformations#96]
I get this error:

![image](https://user-images.githubusercontent.com/5357526/30971632-24b89872-a471-11e7-9837-04fa40532b27.png)

**Comment by afaideen** [comment]
i experienced the same too. Can't open/import.

**Comment by AndroidDeveloperLB** [comment]
@wasabeef Why close it?
It still occurs.

**Comment by AndroidDeveloperLB** [comment]
Here's a screenshot:
![image](https://user-images.githubusercontent.com/5357526/35551420-a9fa95b2-0597-11e8-8605-b75016584f88.png)
