### ISSUE TITLE
lost transformations effect

### ISSUE THREAD

**Issue by kaysaith** [wasabeef/glide-transformations#99]
hi, once centerCrop() after bitmapTransform will lost effect

**Comment by wolfemm** [comment]
via #32: Drop the `centerCrop()` and use `bitmapTransform(new CenterCrop(context), ...)`

**Comment by kaysaith** [comment]
thank for your replying~ 
 when i add it  in 
apply(bitmapTransform(centerCrop(context), PixelationFilterTransformation(30f)))

alert 
too many argument @checkResult

**Comment by wolfemm** [comment]
Try using a MultiTransformation: `apply(bitmapTransform(new MultiTransformation<>(new CenterCrop(), new PixelationFilterTransformation(30f))))`
